assets/sass/main.scss
https://github.com/confluentinc/kafka-tutorials/issues/111
Removed the fixed height.
=> Remove fixed height from card

_includes/tutorials/tumbling-windows/kstreams/markup/dev/make-topology.adoc
=> Fix AsciiDoc link

_data/tutorials.yaml, _includes/tutorials/tumbling-windows/kstreams/code/docker-compose.yml
This was accidentally disabled in 0e572a558e6ad5f0c827bba0a422e1f3d58bda59
=> Re-enable KStreams tumbling windows tutorial

_data/tutorials.yaml, assets/img/icon-connect.svg, assets/sass/_form.scss, assets/sass/main.scss, index.html, tutorials/connect-jdbc-specificavro/kstreams.html
=> Adds connect card to index

_includes/tutorials/aggregating-count/kstreams/code/Makefile, _includes/tutorials/aggregating-count/kstreams/code/settings.gradle
=> Correct naming in kstreams/aggregating-count; fix #200

_includes/tutorials/aggregating-minmax/ksql/markup/dev/transient-query.adoc
=> Correct typo in aggregating-minmax/ksql; fix #201

README.md
=> Correct "Tie it all together" instructions

_layouts/tutorial.html, assets/sass/tutorial.scss, tutorials/window-final-result/kstreams.html
=> Adds community contributor banner

_includes/tutorial-content.html, _layouts/tutorial.html, harness_runner/harness_runner.py
Pre-req for #122. Not all tutorials are going to have a `Test it` and `Take it to production` stage. For example, with Kafka Connect.
=> Make "test it" and "take it to production" steps optional

templates/kstreams/filtered/code/build.gradle
changes per comments from #314
=> MINOR: Update template build.gradle file

_includes/tutorials/rekeying-function/ksql/code/src/statements.sql, _includes/tutorials/rekeying-function/ksql/code/tutorial-steps/prod/send-to-api.sh
Fix for json escaping, and reserved word in the statements.sql
=> Rekeying function update

assets/sass/main.scss, assets/sass/tutorial.scss
=> Fix width overflows on smaller screens

tools/create-test-pipeline.sh, tools/update-ksqldb-version.sh
Addresses #364
```
#
#
```
```
#
#
```
=> ksqlDB version bump utilities

_includes/tutorials/aggregating-count/kstreams/code/tutorial-steps/dev/docker-compose-up.sh, _includes/tutorials/aggregating-minmax/kstreams/code/tutorial-steps/dev/docker-compose-up.sh, _includes/tutorials/aggregating-sum/kstreams/code/tutorial-steps/dev/docker-compose-up.sh, _includes/tutorials/connect-add-key-to-source/kstreams/code/tutorial-steps/dev/docker-compose-up.sh, _includes/tutorials/filtering/kstreams/code/tutorial-steps/dev/docker-compose-up.sh, _includes/tutorials/fk-joins/kstreams/code/tutorial-steps/dev/docker-compose-up.sh, _includes/tutorials/merging/kstreams/code/tutorial-steps/dev/docker-compose-up.sh, _includes/tutorials/serialization/kstreams/code/tutorial-steps/dev/docker-compose-up.sh, _includes/tutorials/splitting/kstreams/code/tutorial-steps/dev/docker-compose-up.sh, _includes/tutorials/transforming/kafka/code/tutorial-steps/dev/docker-compose-up.sh, _includes/tutorials/transforming/kstreams/code/tutorial-steps/dev/docker-compose-up.sh, _includes/tutorials/tumbling-windows/kstreams/code/tutorial-steps/dev/docker-compose-up.sh, _includes/tutorials/window-final-result/kstreams/code/tutorial-steps/dev/docker-compose-up.sh
Updated files to use `docker-compose up -d` . Takes care of #385
=> MINOR:Update all tutorials to use docker-compose-up.sh

_layouts/tutorial.html
=> MINOR: Change Kafka tutorials from 'Vanilla' to 'Basic'

assets/js/main.js, assets/sass/main.scss, index.html
This PR moves the `Kafka 101` card to the upper left-hand corner and allows for expanding/contracting the large tutorial list in `Apply a function to data`
=> MINOR: Update the KT landing page

_layouts/tutorial.html, assets/sass/tutorial.scss, tutorials/transforming/kafka.html, tutorials/transforming/ksql.html, tutorials/transforming/kstreams.html
Support for adding videos to tutorial
=> [DEVX-1854] Optionally support YT embeds

_data/harnesses/serialization/ksql.yml, _data/tutorials.yaml, _includes/tutorials/serialization/ksql/code/src/statements.sql, _includes/tutorials/serialization/ksql/code/test/input.json, _includes/tutorials/serialization/ksql/code/test/output.json, _includes/tutorials/serialization/ksql/code/tutorial-steps/dev/create-avro-movies.sql, _includes/tutorials/serialization/ksql/code/tutorial-steps/dev/create-json-movies.sql, _includes/tutorials/serialization/ksql/code/tutorial-steps/dev/create-proto-movies.sql, _includes/tutorials/serialization/ksql/code/tutorial-steps/dev/expected-print.log, _includes/tutorials/serialization/ksql/code/tutorial-steps/dev/populate-avro-movies.sql, _includes/tutorials/serialization/ksql/code/tutorial-steps/dev/populate-json-movies.sql, _includes/tutorials/serialization/ksql/code/tutorial-steps/dev/print-output-topic.sql, _includes/tutorials/serialization/ksql/markup/dev/create-avro-movies.adoc, _includes/tutorials/serialization/ksql/markup/dev/create-json-movies.adoc, _includes/tutorials/serialization/ksql/markup/dev/create-proto-movies.adoc, _includes/tutorials/serialization/ksql/markup/dev/populate-avro-movies.adoc, _includes/tutorials/serialization/ksql/markup/dev/populate-json-movies.adoc, _includes/tutorials/serialization/ksql/markup/dev/print-output-topic.adoc
Updating existing tutorial to demo avro to protobuf migration
FIXES #369﻿
while it's hot :-P
=> [KSQL] Avro to Protobuf tutorial update

README.md
=> GH-467: make SEQUENCE requires single quotes

tutorials/console-consumer-produer-basic/kafka.html, tutorials/console-consumer-read-specific-offsets-partition/kafka.html
added video walkthroughs 
- consumer/producer basics
- consume fro specific offset
=> Adding video walkthrough links

_data/tutorials.yaml, _includes/tutorial-content.html
This tutorial still had a problem vs. question statement.
=> MINOR: Add question to tutorial instead of problem

README.md
Minor tweaks to fix things that glitched as I re-familiarised myself with the doc :)
=> README tweaks & nits

_includes/tutorials/serialization/ksql/markup/dev/set-properties_offset.adoc
=> fix of ksql tutorial text

_includes/tutorials/deserialization-errors/ksql/code/tutorial-steps/dev/expected-check-errors-query.log, _includes/tutorials/deserialization-errors/ksql/code/tutorial-steps/dev/expected-print.log, _includes/tutorials/merging/ksql/code/tutorial-steps/dev/expected-description.log, _includes/tutorials/rekeying/ksql/code/tutorial-steps/dev/expected-print-output.log
The deserialization-error updates were caused by https://github.com/confluentinc/ksql/pull/6253.
=> Update some of the outputs for KSQL v0.13.0

_includes/tutorials/kafka-producer-application-callback/kafka/code/docker-compose.yml, _includes/tutorials/kafka-producer-application-callback/kafka/code/src/main/java/io/confluent/developer/KafkaProducerCallbackApplication.java, _includes/tutorials/kafka-producer-application-callback/kafka/code/src/test/java/io/confluent/developer/KafkaProducerCallbackApplicationTest.java, _includes/tutorials/kafka-producer-application/kafka/code/docker-compose.yml, _includes/tutorials/kafka-producer-application/kafka/code/src/main/java/io/confluent/developer/KafkaProducerApplication.java, _includes/tutorials/kafka-producer-application/kafka/code/src/test/java/io/confluent/developer/KafkaProducerApplicationTest.java
Minor clean-up PR corresponding to #570
=> MINOR: Clean-up fixes

assets/js/main.js, index.html
Adds a `more` button to the `Kafka 101` section it cleans up the view some
=> MINOR: Add more button to the 101 section

_data/harnesses/message-ordering/kafka.yml, _includes/tutorials/message-ordering/kafka/code/tutorial-steps/dev/answer-code-short.java, _includes/tutorials/message-ordering/kafka/markup/dev/answer-configs.adoc
Address one KT for #600: Create short answer for idempotent producer KT
Staging: http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-600-idempotent-producer/message-ordering/kafka.html
=> #600: Create short answer for idempotent producer KT

.github/pull_request_template.md
https://github.com/confluentinc/kafka-tutorials/issues/614
=> #614: add pull_request_template.md

_data/harnesses/masking-data/ksql.yml, _includes/tutorials/masking-data/ksql/markup/answer/mask.adoc
Address one KT for #600: Create short answer for data masking KT
https://github.com/confluentinc/kafka-tutorials/issues/600
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-600-data-masking/
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-600-data-masking/masking-data/ksql.html
No tests or test related content was changed with this PR.
=> GH-600: Create short answer for data masking

index.html, tutorials/console-consumer-producer-avro/kafka.html
=> all tested locally

_data/harnesses/aggregating-count/ksql.yml, _data/harnesses/aggregating-count/kstreams.yml, _data/harnesses/console-consumer-producer-basic/kafka.yml, _data/harnesses/deserialization-errors/ksql.yml, _data/harnesses/masking-data/ksql.yml, _data/harnesses/message-ordering/kafka.yml, _includes/tutorials/aggregating-count/ksql/markup/answer/count-persistent.adoc, _includes/tutorials/console-consumer-producer-basic/kafka/markup/answer/consume.adoc, _includes/tutorials/console-consumer-producer-basic/kafka/markup/answer/produce.adoc, _includes/tutorials/deserialization-errors/ksql/markup/dev/answer-sql.adoc, _includes/tutorials/masking-data/ksql/markup/answer/mask.adoc
https://github.com/confluentinc/kafka-tutorials/issues/600
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-600-deserialization-errors/handling-deserialization-errors/ksql.html
=> GH-600: add short answer for deserialization-errors KT

_includes/tutorials/console-consumer-producer-avro/kafka/markup/dev/clean-up.adoc, _includes/tutorials/console-consumer-producer-avro/kafka/markup/dev/start-compose.adoc
=> MINOR: Fix incorrect directory locations

_data/harnesses/console-consumer-producer-avro/kafka.yml, _includes/tutorials/console-consumer-primitive-keys-values/kafka/code/tutorial-steps/dev/expected-output-step-two.txt, _includes/tutorials/console-consumer-producer-avro/kafka/code/Makefile, _includes/tutorials/console-consumer-producer-avro/kafka/code/tutorial-steps/dev/console-consumer-keys.sh, _includes/tutorials/console-consumer-producer-avro/kafka/code/tutorial-steps/dev/console-consumer.sh, _includes/tutorials/console-consumer-producer-avro/kafka/code/tutorial-steps/dev/expected-output-step-two.txt, _includes/tutorials/console-consumer-producer-avro/kafka/code/tutorial-steps/dev/harness-console-consumer-from-beginning.sh, _includes/tutorials/console-consumer-producer-avro/kafka/code/tutorial-steps/dev/harness-console-consumer-keys.sh, _includes/tutorials/console-consumer-producer-avro/kafka/code/tutorial-steps/dev/harness-console-consumer.sh, _includes/tutorials/console-consumer-producer-avro/kafka/code/tutorial-steps/dev/harness-console-producer-keys.sh, _includes/tutorials/console-consumer-producer-avro/kafka/code/tutorial-steps/dev/harness-console-producer.sh, _includes/tutorials/console-consumer-producer-avro/kafka/code/tutorial-steps/dev/init.sh, _includes/tutorials/console-consumer-producer-avro/kafka/code/tutorial-steps/dev/make-schema-dir.sh, _includes/tutorials/console-consumer-producer-avro/kafka/code/tutorial-steps/dev/wait-for-containers.sh, _includes/tutorials/console-consumer-producer-avro/kafka/markup/dev/create-schema.adoc, _includes/tutorials/console-consumer-producer-avro/kafka/markup/dev/make-schema-dir.adoc
Fixes for the avro console producer and consumer test runner
=> MINOR: Changes for getting automated test running correctly

_data/harnesses/dynamic-output-topic/kstreams.yml, _data/tutorials.yaml, _includes/tutorials/dynamic-output-topic/kstreams/code/tutorial-steps/dev/answer-short.java, _includes/tutorials/dynamic-output-topic/kstreams/markup/dev/answer-short.adoc, _includes/tutorials/dynamic-output-topic/kstreams/markup/dev/make-topology.adoc
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-600-dynamic/
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-600-dynamic/dynamic-output-topic/kstreams.html
=> GH-600-dynamic: #600 add another short answer to the dynamic topic KT

.github/dependabot.yml
=> MINOR: Remove a reviewer from dependabot

_data/tutorials.yaml, index.html, tutorials/ksql-nested-json/ksql.html
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_update_nested_JSON_tutorial_language/
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_update_nested_JSON_tutorial_language/working-with-nested-json/ksql.html
=> MINOR: Update text for question and details

_includes/tutorials/console-consumer-producer-avro/kafka/code/docker-compose.yml
Replace link from ZK to broker.
High confidence this should pass, but let's wait for tests to complete before merging.
cc @dlfaraujo as FYI
=> MINOR_remove_ZK_CONNECTION_URL

.semaphore/live-site-deploy.yml
When I fixed the build in #622 I neglected to do the same update for the live-site deploy yml file.
=> MINOR: Remove invalid gem options

_data/tutorials.yaml, _includes/tutorials/anomaly-detection/ksql/markup/dev/create-suspicious-transactions-stream.adoc, index.html
https://github.com/confluentinc/kafka-tutorials/issues/650
Minor text optimizations
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-650/
=> #650 : Cleanup some KT titles and meta-description text

_data/harnesses/aggregating-average/kstreams.yml, _data/harnesses/aggregating-count/kstreams.yml, _data/harnesses/aggregating-minmax/kstreams.yml, _data/harnesses/aggregating-sum/kstreams.yml, _data/harnesses/cogrouping-streams/kstreams.yml, _data/harnesses/connect-add-key-to-source/kstreams.yml, _data/harnesses/dynamic-output-topic/kstreams.yml, _data/harnesses/filtering/kstreams.yml, _data/harnesses/finding-distinct/kstreams.yml, _data/harnesses/fk-joins/kstreams.yml, _data/harnesses/joining-stream-table/kstreams.yml, _data/harnesses/kafka-consumer-application/kafka.yml, _data/harnesses/kafka-producer-application-callback/kafka.yml, _data/harnesses/kafka-producer-application/kafka.yml, _data/harnesses/kafka-streams-schedule-operations/kstreams.yml, _data/harnesses/merging/kstreams.yml, _data/harnesses/message-ordering/kafka.yml, _data/harnesses/naming-changelog-repartition-topics/kstreams.yml, _data/harnesses/serialization/kstreams.yml, _data/harnesses/splitting/kstreams.yml, _data/harnesses/streams-to-table/kstreams.yml, _data/harnesses/transforming/kafka.yml, _data/harnesses/transforming/kstreams.yml, _data/harnesses/tumbling-windows/kstreams.yml, _includes/shared/code/ccloud/properties.txt, _includes/shared/markup/ccloud/try-ccloud-properties.adoc, _includes/shared/markup/ccloud/try-ccloud.adoc
https://github.com/confluentinc/kafka-tutorials/issues/657
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-657
View any/all tutorials that run kafka or kstreams, for example: http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-657/create-stateful-aggregation-count/kstreams.html#run-your-app-to-confluent-cloud
=> #657: Create properties file for running against Confluent Cloud

index.html
This PR updates the index page for an even visual layout
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_update_index_page/
=> MINOR: Update the index page for viz layout

_data/harnesses/hopping-windows/ksql.yml, _data/harnesses/session-windows/ksql.yml, _data/harnesses/tumbling-windows/ksql.yml, _includes/tutorials/hopping-windows/ksql/markup/answer/answer.adoc, _includes/tutorials/session-windows/ksql/markup/answer/answer.adoc, _includes/tutorials/tumbling-windows/ksql/markup/answer/answer.adoc
Continuation of https://github.com/confluentinc/kafka-tutorials/issues/600
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-600-windows/
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-600-windows/create-tumbling-windows/ksql.html
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-600-windows/create-session-windows/ksql.html
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-600-windows/create-hopping-windows/ksql.html
=> Short answer for all windows (ksqlDB)

_data/harnesses/console-consumer-producer-avro/kafka.yml, _includes/tutorials/console-consumer-producer-avro/kafka/markup/dev/create-schema.adoc
Removing the step for users to create a directory, but still have it for the harness-runner.
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_fix_avro_tutorial/
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_fix_avro_tutorial/kafka-console-consumer-producer/kafka.html
=> MINOR: Updates for user to not create directory

tools/update-ksqldb-version.sh
The `update-ksqldb-version.sh` script now works for both linux and darwin based OS.
n/a
Runs on semaphore :) https://confluentinc.semaphoreci.com/branches/abe8dbf4-589f-41ac-bb5a-4665fbf40983
=> update ksql version update script to work with linux

assets/sass/main.scss
PR to remove scrolling if we can't find a way to make it more intutive.
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_remove_scrolling/
=> MINOR: Updates to remove scrolling if needed

_includes/tutorials/transforming/ksql/code/test/output.json
=> update output values for ksqlDB tests

.semaphore/semaphore.yml
=> chore: divide Semaphore jobs into two execution blocks (#703)

index.html
#708 
Note: I went with the no `-ing` option to shorten the card title, but I'm not strongly opinionated on this...
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-708
=> GH-708: #708 Make card headings consistent wrt verb tense

_data/tutorials.yaml, _includes/shared/markup/ccloud/try-ccloud-properties.adoc, _includes/shared/markup/ccloud/try-ccloud.adoc, _includes/tutorials/ccloud-produce-consume/kafka/markup/dev/get-ccloud.adoc, _includes/tutorials/count-messages/kafka/markup/dev/04a-set-env.adoc, _includes/tutorials/kafka-connect-datagen-ccloud/kafka/markup/dev/get-ccloud.adoc
#706 
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH_706/
cc: @bbejeck and @vsyu
=> Address issue #706 to update link to Confluent Cloud

_includes/tutorials/ccloud-produce-consume/kafka/markup/dev/setup-ccloud.adoc, _includes/tutorials/kafka-connect-datagen-ccloud/kafka/markup/dev/setup-ccloud.adoc
Not a fix, but this PR provides a suggested workaround for https://github.com/confluentinc/kafka-tutorials/issues/551
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_add_suggestion_to_reload_shell/
=> MINOR: Suggestion to reload shell

_data/tutorials.yaml, _includes/tutorials/dynamic-output-topic/kstreams/markup/dev/answer-short.adoc
https://github.com/confluentinc/kafka-tutorials/issues/737
Incorporate terminology "topic exchange" into existing KT
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH_737/
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH_737/dynamic-output-topic/kstreams.html
=> #737: Add term topic exchange to dynamic topic KT

index.html
Add link from home page
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/DEVX-2547
=> DEVX-2547: Add link to Confluent Cloud from homepage

_data/stacks.yaml, _data/tutorials.yaml, _layouts/tutorial.html, index.html, tutorials/produce-consume-lang/c.html, tutorials/produce-consume-lang/csharp.html, tutorials/produce-consume-lang/go.html, tutorials/produce-consume-lang/groovy.html, tutorials/produce-consume-lang/java.html, tutorials/produce-consume-lang/python.html
#755 
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-755
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-755/produce-consume-lang/scala.html
=> Address #755 to help users discover other language examples

index.html
Balance last row to maintain grid form
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/card_reset -- scroll to bottom
Compare against current https://kafka-tutorials.confluent.io
=> Move card to balanced row

_data/stacks.yaml, _data/tutorials.yaml, _layouts/tutorial.html, tutorials/produce-consume-lang/confluent.html
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/ccloud-master-add-button/
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/ccloud-master-add-button/produce-consume-lang/confluent.html
=> Add Confluent button

.semaphore/live-site-deploy.yml, .semaphore/pr-staging-deploy.yml, .semaphore/semaphore.yml, .semaphore/staging-site-deploy.yml, vault-bin/vault-setup
Make required updates for semaphore access to vault
=> MINOR:Update the vault app role name

_includes/tutorials/aggregating-count/kstreams/code/build.gradle, _includes/tutorials/aggregating-count/kstreams/code/src/main/java/io/confluent/developer/AggregatingCount.java, _includes/tutorials/aggregating-count/kstreams/code/src/test/java/io/confluent/developer/AggregatingCountTest.java, _includes/tutorials/aggregating-count/kstreams/code/tutorial-steps/dev/expected-output-events.json
=> MINOR: Add text label for output

_includes/tutorials/rekeying/ksql/markup/dev/print-input-topic.adoc
=> minor: update the language in ksql rekeying test

assets/sass/main.scss
Update link color for consistency to CD
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/update_link_color
=> Update link color

Gemfile.lock, assets/sass/main.scss
Fixed color on main page links
=> Kafka Tutorials Release [07-27-2021] Round 2 

_includes/tutorials/connect-add-key-to-source/ksql/code/tutorial-steps/dev/wait-for-containers.sh, _includes/tutorials/connect-add-key-to-source/kstreams/code/Makefile, _includes/tutorials/connect-add-key-to-source/kstreams/code/tutorial-steps/dev/wait-for-containers.sh
#903 
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-903
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-903/connect-add-key-to-source/kstreams.html
=> Extend wait-for-containers.sh to check Connect status

_includes/tutorials/connect-add-key-to-source/kstreams/code/Makefile
Cleanup https://github.com/confluentinc/kafka-tutorials/issues/903
I think https://github.com/confluentinc/kafka-tutorials/pull/904/files#diff-6152cae8aa2cb55a64d4fa405de549b5f03d345b0eebb1af5f1715b2ff9feb0a Makefile edit got lucky.  Without this new PR, the test could still be flaky.
=> Update to #903 #904

_data/harnesses/window-final-result/kstreams.yml
=> Fixed typo exctractor->extractor

_includes/footer.html, assets/sass/_footer.scss
Fixing social icon issues that was reported here: [https://confluent.slack.com/archives/C19MZFS9W/p1628121074006400](url)
Font awesome is included on the website, we just need to update the class names.
also added transition so when user hovers they know its clickable.
=> Update class names for font awesome icons

_includes/nav.html, assets/sass/main.scss
Remove Top banner, requested by Robin Moffatt here: [https://docs.google.com/spreadsheets/d/17_qVurrRer7tKVdWKnT6KLNuGFB_DAN4jxWJ0XooWdw/edit#gid=175322604&range=11:11](url)
=> Remove top banner

_data/harnesses/dynamic-output-topic/confluent.yml, _data/tutorials.yaml, _layouts/tutorial.html
- Improve metadata descriptions
- Add missing descriptions
There are no code changes in this PR, just text (specifically metadata)
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/metadata-descriptions
=> Metadata descriptions

README.md, _data/tutorials.yaml, _layouts/tutorial.html, templates/todo_template.txt
Release KT with canonical implementation
See #920 for details
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master
=> Kafka Tutorials release [August 23, 2021]

_includes/shared/markup/ccloud/ccloud-destroy.adoc, _includes/shared/markup/ccloud/config-create.adoc, _includes/shared/markup/ccloud/get-ccloud.adoc, _includes/shared/markup/ccloud/try-ccloud-properties.adoc, _includes/shared/markup/ccloud/try-ccloud.adoc, _includes/tutorials/console-consumer-producer-basic/confluent/markup/dev/consume-topic-key-value.adoc, _includes/tutorials/kafka-connect-datagen/confluent/markup/dev/consume-topic-key-value.adoc, _includes/tutorials/kafka-connect-datagen/confluent/markup/dev/create-connector-config.adoc, _includes/tutorials/kafka-connect-datagen/confluent/markup/dev/delete-connector.adoc, _includes/tutorials/kafka-connect-datagen/confluent/markup/dev/provision-connector.adoc
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/cloud-console
=> Rename Confluent Cloud UI to Confluent Cloud Console

assets/js/tutorial.js
need to update class name to get the copy icon to work
slack here - [https://confluent.slack.com/archives/CHMFCJRCM/p1630614981002000](url)
issue [here](https://github.com/confluentinc/kafka-tutorials/issues/931)
=> Update copy icon

_includes/tutorials/aggregating-count/ksql/markup/answer/count-persistent.adoc, _includes/tutorials/console-consumer-producer-basic/kafka/markup/answer/consume.adoc, _includes/tutorials/console-consumer-producer-basic/kafka/markup/answer/produce.adoc, _includes/tutorials/multi-joins/ksql/markup/answer/multi-way-join.adoc, _includes/tutorials/time-concepts/ksql/markup/answer/short-answer.adoc
Very Minor formatting fix
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/syntax_type
=> [MINOR] Fix up code class types

index.html
Discussion here -- https://app.asana.com/0/1200646067049563/1200732351323028
=> Convert to absolute url

_data/harnesses/aggregating-count/confluent.yml, _data/harnesses/aggregating-sum/confluent.yml, _data/harnesses/cogrouping-streams/confluent.yml, _data/harnesses/console-consumer-producer-basic/confluent.yml, _data/harnesses/console-consumer-read-specific-offsets-partition/confluent.yml, _data/harnesses/count-messages/confluent.yml, _data/harnesses/dynamic-output-topic/confluent.yml, _data/harnesses/error-handling/confluent.yml, _data/harnesses/filtering/confluent.yml, _data/harnesses/finding-distinct/confluent.yml, _data/harnesses/joining-stream-table/confluent.yml, _data/harnesses/kafka-connect-datagen/confluent.yml, _data/harnesses/kafka-consumer-application/confluent.yml, _data/harnesses/kafka-producer-application-callback/confluent.yml, _data/harnesses/kafka-producer-application/confluent.yml, _data/harnesses/merging/confluent.yml, _data/harnesses/session-windows/confluent.yml, _data/harnesses/splitting/confluent.yml, _data/harnesses/streams-to-table/confluent.yml, _data/harnesses/transforming/confluent.yml, _data/harnesses/tumbling-windows/confluent.yml, _includes/shared/markup/ccloud/ccloud-setup-self.adoc, _includes/tutorial-content.html, _includes/tutorials/cogrouping-streams/confluent/markup/answer/short-answer.adoc, _includes/tutorials/console-consumer-read-specific-offsets-partition/confluent/markup/dev/answer-short.adoc, _includes/tutorials/count-messages/confluent/markup/dev/answer-short.adoc, _layouts/tutorial.html, index.html
Use more hands-on language in tutorial
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/hands-on-language
=> Use more hands-on language in tutorial

_includes/footer.html, assets/sass/_footer.scss
Updated the footer links to match the [developer site](https://developer.confluent.io/)'s. 
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/updated-footer-element/
=> Updates to footer element and styles

_data/tutorials.yaml
Titles and meta descriptions are unchanged.
=> Copyedit tutorial questions and introductions

_layouts/tutorial.html, index.html
Updated script links to remove self closing tags. Fixes the copy/paste icon and the "Signup" button. 
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/fix-script-link/
=> updated script links to remove self closing tags

_config.yml, _data/tutorials.yaml, _layouts/tutorial.html
For Asana ticket https://app.asana.com/0/0/1201412089084405/f
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_updates_to_metadata_and_description_V2
=> MINOR: Update title and metadata descriptions per SEO recommendations

assets/sass/_nav.scss
Fixed spacing between `Header` and `Hero`
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/update-logo/
=> Fixed hero spacing

settings.gradle
=> Skip confluent projects from build

_includes/apache.html, assets/sass/_footer.scss, assets/sass/_form.scss, assets/sass/_mixins.scss, assets/sass/_nav.scss, assets/sass/_tabs.scss, assets/sass/_typography.scss, assets/sass/_vars.scss, assets/sass/asciidoc.scss, assets/sass/main.scss, assets/sass/tutorial.scss
Cleaned up css 
[Asana](https://app.asana.com/0/1199171418367599/1201186214260884)
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/style-cleanup/
=> Style cleanup

_includes/tutorial-content.html, _layouts/recipe.html, _layouts/tutorial.html, assets/sass/_mixins.scss, assets/sass/_nav.scss, assets/sass/_vars.scss, assets/sass/fonts.css, assets/sass/main.scss, assets/sass/tutorial.scss
- Add color palette
- Add button mixin
- Add atomic button classes in main.scss
- Update tutorial template
NOTE: added buttons in tutorial hero for examples
=> Additional updates for prototype

assets/sass/_mixins.scss, assets/sass/_nav.scss, assets/sass/_vars.scss, assets/sass/main.scss, assets/sass/tutorial.scss
- Fixed spacing on cards
- Updated mobile styles for code boxes and paragraphs
=> Mobile updates

assets/sass/main.scss
fixes the scrolling for snippets
=> fixing code snippet that doesnt scroll

_includes/tutorials/connect-add-key-to-source/kafka/code/docker-compose.yml, _includes/tutorials/connect-add-key-to-source/ksql/code/docker-compose.yml, _includes/tutorials/connect-add-key-to-source/kstreams/code/docker-compose.yml, _includes/tutorials/connect-sink-timestamp/ksql/code/docker-compose.yml, _includes/tutorials/console-consumer-primitive-keys-values/kafka/code/docker-compose.yml, _includes/tutorials/count-messages/kafka/code/docker-compose.yml, _includes/tutorials/count-messages/ksql/code/docker-compose.yml, _includes/tutorials/generate-test-data-streams/kafka/code/docker-compose.yml, _includes/tutorials/generate-test-data-streams/ksql/code/docker-compose.yml, _includes/tutorials/kafka-connect-datagen/kafka/code/docker-compose.yml, _includes/tutorials/kafka-streams-schedule-operations/kstreams/code/docker-compose.yml, _includes/tutorials/sliding-windows/kstreams/code/docker-compose.yml
Address #1018 
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/KIP-208
=> KIP-208: address #1018

assets/sass/main.scss
- fixes list default styles
- fixes txt snippet formatting
=> fixing lists and snippets that are txt only

_includes/tutorial-content.html, assets/sass/main.scss, assets/sass/tutorial.scss
- fixed community contribution badge
- fixed tutorial navigation lists
- fixed formatting of tutorial-content
=> Comments fixes

index.html, use-cases-phase2.html, use-cases.html
https://confluentinc.atlassian.net/browse/UIF-1175
=> feat: [UIF-1175] - Remove Kafka-tutorials: Update swiftype site ids

_includes/tutorials/clickstream/confluent/code/tutorial-steps/dev/source.sql
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/clickstream-fix
=> Fix Clickstream source.sql

_layouts/recipe.html, _layouts/tutorial.html
Follow-up to #1092 (cc: @bpurkaystha , I missed this optimization)
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/relative-links
=> Relative links for back to tutorials

_includes/tutorial-content.html, _layouts/recipe.html, _layouts/tutorial.html, assets/sass/main.scss
#1092 
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master
=> Kafka Tutorials Release [February 28, 2022]

_includes/tutorials/naming-changelog-repartition-topics/kstreams/markup/dev/make-topology.adoc
Corrected name of the count stream referenced in the join with input stream (exampleCountStream to countStream) 
N/A
N/A
=> Updated name of count stream referenced in join with input stream

_includes/tutorials/datacenter/ksql-test/code/Makefile, _includes/tutorials/datacenter/ksql-test/code/tutorial-steps/test/validate.sql, _includes/tutorials/model-retraining/ksql-test/code/Makefile
Attempt to address intermittently failing tests for ksqlDB recipes
=> Attempt to address intermittently failing tests for ksqlDB recipes

_includes/nav.html, assets/sass/_nav.scss
https://app.asana.com/0/1201747286474214/1201977097019122
Adding docs dropdown/links to the nav/mobile nav, respectively.
=> adding docs dropdown to KT

_includes/tutorials/SSH-attack/confluent/markup/dev/process.adoc, assets/js/tutorial.js
=> New class added `expand-default` for code blocks

_data/tutorials.yaml, _includes/tutorials/finding-distinct/ksql/markup/dev/transient-window.adoc, _includes/tutorials/joining-stream-table/ksql/markup/dev/populate-ratings.adoc
#1197 
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-1197
=> Fix minor nits and typos

_includes/tutorials/online-dating/confluent/markup/dev/explanation.adoc
=> Recipes: Fix query typo in online-dating final answer

_includes/tutorials/audit-logs/confluent/markup/dev/explanation.adoc, _includes/tutorials/ddos/confluent/code/tutorial-steps/dev/source.sql
Missing semi colons in KSQL statements
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/fix-semicolon
=> [MINOR] Add missing semi colons

_data/harnesses/online-dating/confluent.yml, _includes/shared/code/ccloud/comment-manual.sql, _includes/shared/markup/ccloud/connect.adoc, _includes/tutorials/online-dating/confluent/markup/dev/process.adoc, _includes/tutorials/online-dating/confluent/markup/dev/source.adoc
Similar to https://github.com/confluentinc/kafka-tutorials/pull/1240, reorder to INSERT INTO favored path
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/reorder-insert-online-dating/online-dating/confluent.html
=> Reorder online dating

_data/harnesses/messaging-modernization/confluent.yml, _includes/tutorials/messaging-modernization/confluent/markup/dev/process.adoc, _includes/tutorials/messaging-modernization/confluent/markup/dev/source.adoc
Similar to https://github.com/confluentinc/kafka-tutorials/pull/1259, reorder messaging-modernization
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/reorder-insert-messaging-modernization/messaging-modernization/confluent.html
=> Reorder messaging modernization

_data/tutorials.yaml, use-cases.html
https://github.com/confluentinc/kafka-tutorials/issues/update-promotion-title/use-cases.html
=> Update promotion title

_includes/nav.html
https://app.asana.com/0/1201992122798724/1202220412576182/f
- Navigation taxonomy update
=> Tutorials navigation taxonomy updated

_includes/nav.html
=> Bullets in menu list removed

.semaphore/semaphore.yml
https://github.com/confluentinc/kafka-tutorials/issues/1321
N/A
N/A
=> increase semaphore timeout to reduce build flakiness

.semaphore/semaphore.yml, harness_runner/setup.py
https://github.com/confluentinc/kafka-tutorials/issues/1326
N/A
N/A
=> non-root harness-runner install

_includes/nav.html
Change the navigation menu item `Stream Processing Cookbook` under Build to `Tutorials`
=> feat: changes nav item Stream Processing Cookbook to Tutorials

Gemfile.lock
Fix for this [Dependabot Security Alert](https://github.com/confluentinc/kafka-tutorials/security/dependabot/1)
=> HOT FIX: Update jmespath to 1.6.1

_includes/nav.html, assets/sass/_nav.scss
Adding the search link for the developer search page on the KT nav.
https://app.asana.com/0/search/1202842662295329/1202502754694536
=> adding search link in nav

_includes/shared/markup/ccloud/config-broker-only-create.adoc, _includes/shared/markup/ccloud/config-create.adoc, _includes/shared/markup/ccloud/get-ccloud.adoc
1.  Remove old warning for CLI version changes
2. Update description for setting up Clients in Confluent Cloud
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_small_fixes/
=> MINOR: Small fixes 

_includes/tutorials/clickstream/confluent/code/tutorial-steps/dev/sink.json, _includes/tutorials/clickstream/confluent/code/tutorial-steps/dev/sink.sql, _includes/tutorials/customer-journey/confluent/code/tutorial-steps/dev/sink.sql
trivial comment-only fix in sink connectors for bug pointed out by @wicknicks
=> fix sink connector topics to match topic names exactly

.semaphore/pr-staging-deploy.yml, .semaphore/semaphore.yml, .semaphore/staging-site-deploy.yml
This is better than SEMAPHORE_GIT_BRANCH for staging PRs because SEMAPHORE_GIT_BRANCH can be the target (typically master) for PRs.
=> use SEMAPHORE_GIT_WORKING_BRANCH for deployment paths

.github/CODEOWNERS
Reverts confluentinc/kafka-tutorials#1263
=> Revert "Add Colin to codeowners"

assets/js/segment.js
Send copy event to Segment.
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/track-copy-code
=> Add tracking to code copy
