confluentinc/kafka-tutorials

- _config.yml
- _includes/tutorials/transforming/kafka/code/configuration/test.properties
Virtually all tutorials have this link to `_includes/shared-content/docker-install.txt` that specifies how the user will get Confluent Platform. Currently. the version used is **v5.2.1** which is outdated.
This PR changes it to **v5.3.0** which is in line to what we're currently using in our docker-compose.yml file.
> Updated the Confluent Platform version to 5.3.0

- .semaphore/semaphore.yml
- _config.yml
- _includes/nav.html
- _layouts/tutorial.html
- assets/sass/main.scss
- index.html
Deploy selected branches automatically to the new staging site from CI. With this PR, auto-deployment is enabled for branches with names that include `staging` (e.g. `foo-staging`) and the `master` branch itself.
- Each set of staging site artifacts is deleted after seven days.
- Pathnames are based on the branch name and commit SHA. The hostname is `kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com`. Successful builds include the artifact url in the build output, e.g:
> Deployed to http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/ci-staging/e76625413afef67457c48ef3c66059a6f5813c4a/
Note: These changes do not include any promotion to `kafka-tutorials.confluent.io`.
 
> Deploy preview site automatically

- _includes/tutorials/joining-stream-table/kstreams/markup/test/make-topology-test.adoc
- _includes/tutorials/transforming/kstreams/markup/test/make-test.adoc
- _includes/tutorials/tumbling-windows/kstreams/markup/test/make-topology-test.adoc
Various copy and pasting resulted in `requires` misspelled in a few places.
> Repairs some common typos

- .semaphore/semaphore.yml
- harness_runner/harness_runner.py
Adding a sleep in the harness runner works around an apparent race condition cleaning up the test containers when running tests on Semaphore. cf. https://github.com/confluentinc/kafka-tutorials/pull/144#issuecomment-569727611
This also adds a ceiling on CI test execution time.
> Reduce CI flakiness and add execution timeout

- index.html
According to the [Apache Kafka official site](https://kafka.apache.org/), the technology is known for being a distributed streaming platform, rather than just a pub/sub messaging system.
Therefore, this PR corrects the description of the index.html page.
> Change Apache Kafka explanation from Messaging to Streaming Platform

- _includes/tutorials/hopping-windows/ksql/markup/dev/print-topic.adoc
This PR fixes a small mistake left behind in the `KSQL Hopping Window` tutorial where a non-sense paragraph was left behind and causes confusion for the reader.
Thanks,
-- Ricardo
> Fixing KSQL Hopping Window 'Print Topic' Narrative

- index.html
This PR is a correction to https://github.com/confluentinc/kafka-tutorials/pull/221
The Tutorial is mostly fine but the name that shows up in the card is wrong.
The reason I messed this up: both KTs that I intended to write (#122 and #123) use SMTs, `setschemametadata`.  But the one I wrote so far doesn't use SMTs for rekey.  The file names are correct `connect-jdbc-kstreams-rekey-specificavro`, but when I saw the SMT, I mislabelled it as the SMT rekeyer
> Correction to KT name for  (#221)

- _includes/tutorials/aggregating-count/ksql/code/docker-compose.yml
- _includes/tutorials/aggregating-minmax/ksql/code/docker-compose.yml
- _includes/tutorials/aggregating-sum/ksql/code/docker-compose.yml
- _includes/tutorials/filtering/ksql/code/docker-compose.yml
- _includes/tutorials/finding-distinct/ksql/code/docker-compose.yml
- _includes/tutorials/flatten-nested-data/ksql/code/docker-compose.yml
- _includes/tutorials/hopping-windows/ksql/code/docker-compose.yml
- _includes/tutorials/joining-stream-stream/ksql/code/docker-compose.yml
- _includes/tutorials/joining-stream-table/ksql/code/docker-compose.yml
- _includes/tutorials/joining-table-table/ksql/code/docker-compose.yml
- _includes/tutorials/merging/ksql/code/docker-compose.yml
- _includes/tutorials/rekeying-function/ksql/code/docker-compose.yml
- _includes/tutorials/rekeying/ksql/code/docker-compose.yml
- _includes/tutorials/serialization/ksql/code/docker-compose.yml
- _includes/tutorials/splitting/ksql/code/docker-compose.yml
- _includes/tutorials/transforming/ksql/code/docker-compose.yml
- _includes/tutorials/tumbling-windows/ksql/code/docker-compose.yml
- _includes/tutorials/udf/ksql/code/docker-compose.yml
- templates/ksql/filtered/code/docker-compose.yml
The ksqlDB Kafka Tutorials examples currently use the `log4j-rolling.properties` file for the ksqlDB server. This properties file does not log to standard out so no ksqlDB server logs are shown when examples are run, which (1) is incongruous with the other components and (2) makes it difficult to diagnose issues when something goes wrong (e.g., the server is unable to start). 
This PR updates the docker-compose files to use the "log4j.properties" file instead, which means ksqlDB server logs will be shown as part of `docker-compose up`.
> Minor: enable ksqlDB server logging

- _includes/tutorials/finding-distinct/kstreams/code/build.gradle
- _includes/tutorials/finding-distinct/kstreams/code/src/main/java/io/confluent/developer/FindDistinctEvents.java
- _includes/tutorials/finding-distinct/kstreams/markup/dev/make-topology.adoc
Hello, 
the current version of the tutorial uses `Transformer`. However, since `Transformer` may change the key, its usage will lead to redundant repartitioning when grouping operations are used aftewards.
I propose to rewrite this example using `ValueTransformer[WithKey]`, which will not cause the unwanted repartitioning.
By the way, it seems to me that we have a bug in `transformValues`: see the `filter((k, v) -> v != null)` after it. Without this filter, `null` values appear downstream, contrary to what is said in JavaDoc:
> If the return value of `ValueTransformerWithKey#transform(Object, Object)`  is `null`, no records are emitted.
> Use ValueTransformerWithKey instead of Transformer

- _includes/footer.html
- _includes/nav.html
- assets/js/main.js
- assets/js/tutorial.js
- assets/sass/main.scss
Adds links to Confluent Developer and the main Confluent home in the site nav. Restyles the contribute link.
On smaller screens, these links are rendered in a hamburger menu.
Closes #293
> Add Confluent Developer to site navigation

- _includes/vendors.html
This includes Roboto with a link rel. This ensures it renders correctly on machines where Roboto is not locally-installed.
preview
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/cccc971aee02015dcc1a44545012c99954b213d0/
> Hotfix subdomain tag font

- _data/harnesses/deserialization-errors/ksql.yml
- _includes/tutorials/deserialization-errors/ksql/code/Makefile
- _includes/tutorials/deserialization-errors/ksql/code/tutorial-steps/dev/expected-print.log
- _includes/tutorials/deserialization-errors/ksql/markup/dev/print-topic.adoc
When making some other changes in here I noticed that the existing `print-topic.adoc` file was not hooked up in the tutorial's yaml file.
I've added it in here and ensured the print topic output is tested.  Alternatively, if we don't want the print topic step I can just delete the file and associated scripts.
Thoughts?
> add print topic step to deserialization error tutorial

- _includes/tutorials/console-consumer-produer-basic/kafka/code/tutorial-steps/dev/create-topic.sh
- _includes/tutorials/console-consumer-produer-basic/kafka/code/tutorial-steps/dev/harness-console-consumer-from-beginning.sh
- _includes/tutorials/console-consumer-produer-basic/kafka/code/tutorial-steps/dev/harness-console-consumer-keys.sh
- _includes/tutorials/console-consumer-produer-basic/kafka/code/tutorial-steps/dev/harness-console-consumer.sh
- _includes/tutorials/console-consumer-produer-basic/kafka/code/tutorial-steps/dev/harness-console-producer-keys.sh
- _includes/tutorials/console-consumer-produer-basic/kafka/code/tutorial-steps/dev/harness-console-producer.sh
A minor PR to have consistent use of `docker-compose` commands in the 101 tutorials
> MINOR: Remove use of '/usr/bin' from docker-compose commands

- _includes/tutorials/filtering/ksql/code/src/statements.sql
- _includes/tutorials/filtering/ksql/code/test/input.json
- _includes/tutorials/filtering/ksql/code/test/output.json
- _includes/tutorials/filtering/ksql/code/tutorial-steps/dev/continuous-select.sql
- _includes/tutorials/filtering/ksql/code/tutorial-steps/dev/create-inputs.sql
- _includes/tutorials/filtering/ksql/code/tutorial-steps/dev/expected-print.log
- _includes/tutorials/filtering/ksql/code/tutorial-steps/dev/expected-transient.log
- _includes/tutorials/filtering/ksql/code/tutorial-steps/dev/populate-stream.sql
- _includes/tutorials/filtering/ksql/code/tutorial-steps/dev/transient-query.sql
- _includes/tutorials/filtering/ksql/markup/dev/print-topic.adoc
- _includes/tutorials/filtering/ksql/markup/dev/transient-query.adoc
Also, hooked up expected print and query outputs.
Decided to add a unique `bookid` key column so that PRINT output is cleaner, avoiding issue where PRINT can sometimes not differentiate between windowed and non-windowed keys.
> update filtering tutorial inline with changes to ksqlDB master

- assets/sass/tutorial.scss
iframe aspect ratio remains consistent at all screen widths, so there is no letterboxing effect:
> Fix 2-by-1 aspect ratio for embedded media

- _data/harnesses/finding-distinct/ksql.yml
- _includes/tutorials/finding-distinct/ksql/code/tutorial-steps/dev/set-properties2.sql
- _includes/tutorials/finding-distinct/ksql/markup/dev/set-properties2.adoc
- _includes/tutorials/finding-distinct/ksql/markup/dev/transient-window.adoc
- _includes/tutorials/finding-distinct/ksql/markup/prod/submit-to-api.adoc
addresses #487 
Called attention to the usage in step 3 of `Try it`, plus `Take it to production`.
[Preview link](http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/GH-487/6b17aa6e5956c6fc4d6bbb83c7a6a0aa9425309e/finding-distinct-events/ksql.html).
> Document cache.max.bytes.buffering in finding-distinct events

- .semaphore/semaphore.yml
- settings.gradle
Testing the restructuring of the semaphore yml file to get builds running under the 50 parallel limit
> MINOR: Restructure of semaphore yml for running build 

- _includes/tutorials/rekeying/ksql/code/Makefile
See #510 for details of _why_ the test is failing. 
Unless ksqlDB adds support for `SLEEP`, or we split the `docker_ksql_cli_session` and insert a bash `sleep` step (a lot of heavy lifting), this option will hopefully suffice for now. It simply `grep`s out the offending `KAFKA_STRING` mention in the test at the end.
> Hacky fix to #510 for ksql rekey failing test

- _data/tutorials.yaml
- _includes/tutorials/console-consumer-produer-basic/kafka/markup/dev/consume-topic-from-beginning.adoc
- _includes/tutorials/console-consumer-produer-basic/kafka/markup/dev/produce-topic-from-beginning.adoc
- _includes/tutorials/console-consumer-produer-basic/kafka/markup/dev/produce-topic.adoc
- Fixed spelling and punctuation in some areas in **Console Producer and Consumer Basics, no (de)serializers** page. 
- https://github.com/confluentinc/kafka-tutorials/issues/524
> ISSUE_524: Fix spelling and punctuation in some areas in 'Console Producer and Consumer Basics' page

- .semaphore/semaphore.yml
Originally I reduced the timeout for semaphore blocks to 5 minutes, but that is too strict as some tests run close to 5 minutes now.  Increasing the timeout to 10 minutes. For example the #565 PR all tests passed, but the build failed because one test ran over 5 minutes.
> MINOR: Increase timeouts for sempaphore

- _includes/tutorials/kafka-streams-schedule-operations/kstreams/code/Dockerfile
Needed to set `cp-kafka-connect-base` back to `5.5.1` otherwise the tutorial fails due to source topic not getting created.
Covers https://github.com/confluentinc/kafka-tutorials/issues/584
> MINOR: Revert cp-kafka-connect-base to 5.5.1

- .semaphore/live-site-deploy.yml
- .semaphore/semaphore.yml
---------------
Docker hub will have a layer limit about 50/hr pull operation for anonymous users. Add dockerhub cred and dockerhub login to make sure it pull image with confluentsemaphore service account. It should make it have 200/hr pull limit, we could also upgrade the service account to "pro" to have unlimited pulls.
-------------
Add dockerhub cred and docker login.
> add docker hub login

- _includes/tutorials/ccloud-produce-consume/kafka/code/tutorial-steps/dev/run-ccloud-stack.sh
- _includes/tutorials/ccloud-produce-consume/kafka/markup/dev/setup-ccloud.adoc
Consistency in calling create_ccloud_stack.
And default is now ksqlDB=false (see https://github.com/confluentinc/examples/pull/843)
> GH-602 address #602: consistency in calling create_ccloud_stack

- _includes/tutorials/produce-consume-lang/scala/code/build.gradle
Here is a modification missing from #532, the migration from sbt to gradle
> fix the produce/consume-scala tutorial by setting up a jar base name

- .semaphore/semaphore.yml
The build was failing to compile the jekyll site due to `invalid option: --no-ri --no-doc` failure
> MINOR: update gem install command

- _includes/tutorials/rekeying/ksql/code/Makefile
Cherry-pick https://github.com/confluentinc/kafka-tutorials/pull/555 to ksqldb-latest branch, to avoid flaky failures during manual release testing. 
Slack: https://confluent.slack.com/archives/CTSV6CALC/p1604948386008600
> cherrypick fix for flaky ksql rekey test to ksqldb-latest

- .semaphore/semaphore.yml
- _data/harnesses/anomaly-detection/ksql.yml
Add sleep between populating table and stream. There seem to be some other tests failing in block 1, so I moved this test up to block 1 to ensure it got executed with every semaphore run. Over 6 valid runs (valid run=block is run where this test was present) in semaphore, this test passed every time. Locally this is running without problems for me. 
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/devx-2288
> DEVX-2288: KT Anomaly Detection test is flaky

- _data/harnesses/console-consumer-producer-avro/kafka.yml
- _includes/tutorials/console-consumer-producer-avro/kafka/code/tutorial-steps/dev/make-schema-dir.sh
- _includes/tutorials/console-consumer-producer-avro/kafka/markup/dev/make-schema-dir.adoc
This [PR](https://github.com/confluentinc/kafka-tutorials/pull/675) removed the `make schema directory` step, but it's required for running the test-harness on semaphore
> MINOR: Add back create schema dir step, breaks semaphore test run

- _includes/tutorials/produce-consume-lang/scala/code/build.gradle
- _includes/tutorials/produce-consume-lang/scala/code/src/test/scala/io/confluent/developer/KafkaFlatSpec.scala
- _includes/tutorials/transforming/kafka/code/build.gradle
- _includes/tutorials/transforming/kafka/code/configuration/test.properties
- _includes/tutorials/transforming/kafka/code/src/test/java/io/confluent/developer/TransformEventsTest.java
The `gradle` build started failing with 
```
Cause: com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: testcontainersofficial/ryuk:0.3.0"}
```
The solution is to update the `testcontainers:kafka` version to `1.15.1`.
> MINOR: update for test container changes

- .semaphore/semaphore.yml
This will roughly double time in CI, hopefully with the benefit of reduced flakiness.
> chore: divide Semaphore jobs into two execution blocks

- tools/update-ksqldb-version.sh
fixes the sed invocation to use another delimiter (@) since the docker registry probably
has unescaped slashes. Also, expect the registry to end with a '/'
> fix sed invocation to deal with slash in registry

- _data/tutorials.yaml
The link `produce-and-consume-lang` is incorrect it should be `produce-consume-lang/`
Fixes https://github.com/confluentinc/kafka-tutorials/issues/715
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_fix_scala_produce_consume_button_link/
> MINOR: Fix link in slug entry to match the link tutorials/produce-consume-lang/scala.html

- index.html
- Maintain consistency in KT titles on the cards on the main KT page
- Moved ~2 KTs to a different card (this can be undone if anyone disagrees with the new placement)
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/card_titles_consistency/
> [MINOR] Maintain consistency in KT titles on the cards

- _data/harnesses/kafka-connect-datagen-ccloud/kafka.yml
- _includes/tutorials/kafka-connect-datagen-ccloud/kafka/code/tutorial-steps/dev/check-connector-rest.sh
- _includes/tutorials/kafka-connect-datagen-ccloud/kafka/code/tutorial-steps/dev/check-connector-rest_expected.log
- _includes/tutorials/kafka-connect-datagen-ccloud/kafka/code/tutorial-steps/dev/create-cloud-api-key.sh
- _includes/tutorials/kafka-connect-datagen-ccloud/kafka/code/tutorial-steps/dev/create-connector-rest.sh
- _includes/tutorials/kafka-connect-datagen-ccloud/kafka/markup/dev/check-connector.adoc
- _includes/tutorials/kafka-connect-datagen-ccloud/kafka/markup/dev/clean-up.adoc
- _includes/tutorials/kafka-connect-datagen-ccloud/kafka/markup/dev/create-connector-config.adoc
- _includes/tutorials/kafka-connect-datagen-ccloud/kafka/markup/dev/provision-connector.adoc
- _includes/tutorials/kafka-connect-datagen-ccloud/kafka/markup/dev/setup-ccloud.adoc
Include the options to deploy and view the datage connector using the REST APIs
in addition to the already present ccloud versions of the command
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/DEVX-2522/kafka-connect-datagen-ccloud/kafka.html
> DEVX-2522: datagen KT: enhance with managed REST API

- _data/tutorials.yaml
- index.html
This PR is a tweak to the great TTL KT, to expand the language to include `expire` (laying groundwork so that we can later map it to streaming patterns).  This PR impacts just the introductory text, it does not change the KT workflow.  Feedback welcome, @sarwarbhuiyan @bbejeck 
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/ttl_tweak
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/ttl_tweak/schedule-ktable-ttl/kstreams.html
> [MINOR] Tweak to TTL KT

- _data/harnesses/tumbling-windows/confluent.yml
- _data/tutorials.yaml
- _includes/tutorials/tumbling-windows/confluent/code/configuration/dev.properties
- _includes/tutorials/tumbling-windows/confluent/code/tutorial-steps/dev/console-consumer.sh
- _includes/tutorials/tumbling-windows/confluent/code/tutorial-steps/dev/console-producer-ratings.sh
- _includes/tutorials/tumbling-windows/confluent/markup/dev/make-dev-file.adoc
- _includes/tutorials/tumbling-windows/confluent/markup/dev/run-consumer.adoc
- _includes/tutorials/tumbling-windows/confluent/markup/dev/run-producer.adoc
- _includes/tutorials/tumbling-windows/kstreams/code/src/main/java/io/confluent/developer/TumblingWindow.java
- _includes/tutorials/tumbling-windows/kstreams/code/src/test/java/io/confluent/developer/TumblingWindowTest.java
- settings.gradle
- tutorials/tumbling-windows/confluent.html
* CCloudify Tumbling Windows
Note there is a warning now in the code that I'm not sure if it's something needing addressed:
```
> Task :_includes:tutorials:tumbling-windows:kstreams:code:compileJava
Note: /Users/yeva/git/kafka-tutorials/_includes/tutorials/tumbling-windows/kstreams/code/src/main/java/io/confluent/developer/TumblingWindow.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
> Task :_includes:tutorials:tumbling-windows:kstreams:code:compileTestJava
Note: /Users/yeva/git/kafka-tutorials/_includes/tutorials/tumbling-windows/kstreams/code/src/test/java/io/confluent/developer/TumblingWindowTest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```
I added this into the build:
``` …
```
> CCloudify Tumbling Windows

- _includes/tutorials/serialization/kstreams/code/tutorial-steps/dev/gradle-wrapper.sh
Revert this fix to remove the version flag from the serialization KT `gradle-wrapper.sh` script
> MINOR:Revert gradle version flag

- _includes/tutorials/error-handling/kstreams/code/build.gradle
- _includes/tutorials/produce-consume-lang/scala/code/settings.gradle
- _includes/tutorials/window-final-result/kstreams/code/settings.gradle
Found one tutorial that still references `jcenter`.
@ybyzek your call to merge for this release or not.
> MINOR: Remove jcenter and use mavenCentral

- .semaphore/semaphore.yml
- _data/harnesses/aggregating-count/kstreams.yml
- _includes/tutorials/aggregating-count/kstreams/code/src/main/java/io/confluent/developer/AggregatingCount.java
Adding test entry for the `kstreams` flavor of `aggregation-count` to `semaphore.yml`. 
This entry has been missing for some time.
> MINOR: Add test for aggregation-count KStreams

- _includes/tutorials/aggregating-count/confluent/code/configuration/dev.properties
- _includes/tutorials/dynamic-output-topic/confluent/code/configuration/dev.properties
- _includes/tutorials/finding-distinct/confluent/code/configuration/dev.properties
- _includes/tutorials/streams-to-table/confluent/code/configuration/dev.properties
- _includes/tutorials/tumbling-windows/confluent/code/configuration/dev.properties
Add replication.factor=3 in CCloudified tutorial property files.
> Add replication.factor=3 in confluent tutorials

- _layouts/tutorial.html
Found that tutorial content wasn't loading but was showing "help_wanted_lang" HTML instead, regardless of "help_wanted_lang" being set to false or not present. I modified the logic that presents the HTML to allow it to present the tutorial content.
[Staged latest master](http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/
), all tutorials show the help wanted HTML rather than there content ([example](http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/master/error-handling/kstreams.html)). The same tutorial on this branch which modified logic renders correctly ([example](http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/fix-help-lang/error-handling/kstreams.html)).
Verified that this branch still will display the "help_wanted_lang" page …
> Modify help_wanted html logic

- _includes/tutorials/joining-stream-table/kstreams/code/src/main/java/io/confluent/developer/JoinStreamToTable.java
- _includes/tutorials/joining-stream-table/kstreams/code/tutorial-steps/dev/wait-for-containers.sh
Noticed this the Kafka Streams `streams-table join` tutorial test failed in one of our PR builds
```
org.apache.kafka.common.errors.SerializationException: Error serializing Avro message01:30
Caused by: java.net.ConnectException: Connection refused (Connection refused)01:30
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)01:30
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)01:30
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)01:30
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)01:30
at java.base/java.net.Socket.connect(Socket.java:609)01:30
at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)01:30
at …
```
> MINOR: Add wait for SR and max wait of 5 seconds for streams app to close

- _layouts/tutorial.html
Raised a PR - [https://github.com/confluentinc/kafka-tutorials/pull/913](url) to update the class names for font awesome but i missed adding the script for the tutorial html page. 
this PR will make it so both the home page and tutorial pages render the icons
> Add font awesome script to tutorial html

- README.md
- _data/tutorials.yaml
- _layouts/tutorial.html
- templates/todo_template.txt
Implements canonical links
@ivypie compare
Set 1: (canonical defined, no ksqlDB)
- http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/canonical/creating-first-apache-kafka-consumer-application/kafka.html -- has canonical link
- http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/canonical/creating-first-apache-kafka-consumer-application/confluent.html
Set 2: (canonical defined, yes ksqlDB)
- http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/canonical/create-tumbling-windows/confluent.html
- http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/canonical/create-tumbling-windows/kstreams.html -- has canonical link
- http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/canonical/create-tumbling-windows/ksql.html
Set 3: …
> Canonical implementation

- index.html
https://confluentinc.atlassian.net/browse/UIF-1011
In order to support more sophisticated, faceted search in docs.confluent.io, we are looking at adding some meta tags to a number of websites that are currently included in docs' swiftype search engine. This will allow search results to be targeted at specific sites (and languages).  
The following sites are involved:
Site | Id
-- | --
https://docs.confluent.io/ | 1
https://www.confluent.io/blog/ | 2
https://developer.confluent.io/ | 3
https://docs.ksqldb.io/en/latest/ | 4
https://kafka-tutorials.confluent.io/ | 5
https://api.telemetry.confluent.cloud/docs | 6
The change involved is minimal and would be to add the following meta tag into the main template file of each site:
`<meta class="swiftype" name="site-id" data-type="integer" …
> feat: [UIF-1011] Add swiftype metatag for site of Kafka-Tutorials

- _includes/tutorials/kafka-connect-datagen/confluent/code/tutorial-steps/dev/check-connector.sh
- _includes/tutorials/kafka-connect-datagen/confluent/code/tutorial-steps/dev/create-cloud-api-key.sh
- _includes/tutorials/kafka-connect-datagen/confluent/code/tutorial-steps/dev/create-connector.sh
- _includes/tutorials/kafka-connect-datagen/confluent/code/tutorial-steps/dev/delete-connector.sh
- _includes/tutorials/kafka-connect-datagen/confluent/code/tutorial-steps/dev/list-connector.sh
- _includes/tutorials/kafka-connect-datagen/confluent/markup/dev/provision-connector.adoc
Some additional files that need to migrate to `ccloud` command to `confluent`
> MINOR: Additional changes from ccloud to confluent

- _includes/nav.html
Fix nav for `Stream Processing Use Cases`
> Fix link to Stream Processing Use Cases

- index.html
- use-cases-phase2.html
- use-cases.html
Make links relative on landing page (for buttons)
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/fix_index_buttons
> Make index landing page href relative for buttons

- index.html
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/name-tutorial-categories
@rspurgeon @bbejeck this PR creates a very short description of each _card_ grouping that will be used on the new landing page (coming in March).  Please review the description, copyedit as needed, suggestions welcome.
> Name tutorial categories

- _includes/footer.html
Fixing links in the footer -- this was brought up in Slack.
> Making footer links absolute

- _includes/tutorials/credit-card-activity/confluent/code/tutorial-steps/dev/process.sql
credit card recipe: invalid syntax in CTAS missing quote in KEY_FORMAT
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/rspurgeon-patch-1/credit-card-activity/confluent.html
> credit card recipe: invalid syntax in CTAS

- _includes/tutorial-content.html
- _layouts/recipe.html
- _layouts/tutorial.html
- assets/sass/main.scss
- package-lock.json
[This](https://app.asana.com/0/1201817272699202/1201822439776478) is the Asana story. In short, this PR is about adding two breadcrumbs: `Back to tutorials` on each tutorial & use-case page.
> Breadcrumbs on the tutorial and use-case pages

- _includes/nav.html
https://app.asana.com/0/1201992122798715/1202002461829781
This updates the nav to change the `Tutorials` item to `Stream Processing Cookbook` and removes the other `Stream processing...` link.
> Nav Design, Build, Run update

- assets/sass/tutorial.scss
Fixes https://github.com/confluentinc/kafka-tutorials/issues/1212
> fixing example image height

- .semaphore/semaphore.yml
This cherry-picks the PR that updates semaphore config so that jfrog-based images can be used in CI. The commit was pushed to the `ksqldb-latest` but didn't exist in `master`. We are updating this to follow the approach outline by @colinhicks [here](https://github.com/confluentinc/kafka-tutorials/pull/1228#pullrequestreview-935172768) for the kafka-tutorials tests.
> chore: try different jfrog secret

- _includes/recipe-content-answer.html
- _layouts/recipe.html
- _layouts/tutorial.html
- assets/sass/main.scss
- assets/sass/tutorial.scss
Per discussions, we're cleaning up the hero and making the "Launch..." button more prominent.
> cleaning up tutorial hero: moving launch button and breadcrumb

- _layouts/recipe.html
- _layouts/tutorial.html
- assets/sass/main.scss
- assets/sass/tutorial.scss
We had discussed this on Slack and I discussed this with @ashleebeggs.
The breadcrumb is now moved below the hero for both recipes and tutorials:
> moving breadcrumb below hero

- _data/harnesses/credit-card-activity/confluent.yml
- _includes/shared/code/ccloud/comment-manual.sql
- _includes/shared/markup/ccloud/connect.adoc
- _includes/tutorials/credit-card-activity/confluent/markup/dev/process.adoc
- _includes/tutorials/credit-card-activity/confluent/markup/dev/source.adoc
Test one recipe with reorder INSERT INTO vs connector
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/reorder-insert/credit-card-activity/confluent.html
Compare to current presentation: https://developer.confluent.io/tutorials/credit-card-activity/confluent.html
> Reorder ksqlDB commands so INSERT option presented before connector

- _includes/tutorials/credit-card-activity/confluent/code/tutorial-steps/dev/source.json
- _includes/tutorials/credit-card-activity/confluent/code/tutorial-steps/dev/source.sql
- _includes/tutorials/denormalization/confluent/code/tutorial-steps/dev/source.json
- _includes/tutorials/denormalization/confluent/code/tutorial-steps/dev/source.sql
https://confluentinc.atlassian.net/browse/KSE-1028
> KSE-1028: fix duplicate parameter

- _layouts/recipe.html
- _layouts/tutorial.html
The swiftype tags are missing for tutorials and recipes. Adding those and a `category` tag for the new developer search https://app.asana.com/0/1178383736931373/1156641992335726
> adding swiftype meta tags for tutorials and recipes

- _data/harnesses/error-handling/confluent.yml
- _data/harnesses/error-handling/kstreams.yml
- _data/harnesses/naming-changelog-repartition-topics/kstreams.yml
- _includes/tutorials/error-handling/kstreams/code/build.gradle
- _includes/tutorials/error-handling/kstreams/code/gradle/wrapper/gradle-wrapper.properties
- _includes/tutorials/error-handling/kstreams/code/src/main/java/io/confluent/developer/ProcessorException.java
- _includes/tutorials/error-handling/kstreams/code/src/main/java/io/confluent/developer/StreamsUncaughtExceptionHandling.java
- _includes/tutorials/error-handling/kstreams/code/tutorial-steps/dev/console-consumer.sh
- _includes/tutorials/error-handling/kstreams/code/tutorial-steps/dev/expected-output.txt
- _includes/tutorials/error-handling/kstreams/markup/dev/make-exception-handler.adoc
- _includes/tutorials/naming-changelog-repartition-topics/kstreams/code/.gitignore
- _includes/tutorials/naming-changelog-repartition-topics/kstreams/code/build.gradle
- _includes/tutorials/naming-changelog-repartition-topics/kstreams/code/docker-compose.yml
- _includes/tutorials/naming-changelog-repartition-topics/kstreams/code/src/main/java/io/confluent/developer/NamingChangelogAndRepartitionTopics.java
covers the `Error Handling`  and `Naming Stateful Operations` tutorial for https://github.com/confluentinc/kafka-tutorials/issues/1256
Only the `Error Handling` tutorial had site updates so it's the only one listed, `Naming Stateful Operations` had internal changes only
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/Update_error_handling_to_latest_AK/ 
http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/Update_error_handling_to_latest_AK/error-handling/kstreams.html
> Changes for updating tutorials to work with AK 3.1

- _includes/tutorials/kafka-consumer-application/kafka/code/src/test/java/io/confluent/developer/KafkaConsumerApplicationTest.java
The test uses threads which leads to flaky failures due to race conditions.  To fix this, the test should use the `MockConsumer.schedulePollTask`instead.  
This PR includes a testing change only, so no need to view deployed tutorial.
> Remove threads and use MockConsumer.schedulePollTask

- .semaphore/live-site-deploy.yml
- .semaphore/pr-staging-deploy.yml
- .semaphore/semaphore.yml
- .semaphore/staging-site-deploy.yml
In the current Semaphore cloud offering, all of the Semaphore build nodes are controlled by Semaphore. Thus, we are unable to control what resources they can access. 
It also represents security concerns because Semaphore has access to what is on those nodes, including our credentials from Vault.
The DevProd team will be migrating the existing SemaphoreCI pipelines using linux machines to start using self-hosted Semaphore build agents.
Deadline to migrate the SemaphoreCI jobs to self hosted agents is July 22nd, 2022
The DevProd team will start creating PRs to migrate your existing Semaphore jobs to the self-hosted agents by July 10, 2022.
**This migrates to Semaphore self-hosted agent**
Details on the self-hosted agent host configuration are described here : …
> DP-8085 - Migrate to Semaphore self-hosted agent

- _layouts/recipe.html
- _layouts/tutorial.html
We had an issue on .io where we needed to change from `category` to `contentType` and it makes sense to keep everything aligned.
> updating swiftype tags -- category -> contentType

- .semaphore/semaphore.yml
Self-hosted semaphore needs a `\\` for escaping
> HOT FIX: Use double backslash for escape to fix the build

- README.md
* example release PR description so releasers can copy/paste
* change instructions to requiring squash and merge since that's the
only option allowed
> update deployment instructions

- _data/harnesses/kafka-consumer-application/confluent.yml
Fixes https://github.com/confluentinc/kafka-tutorials/issues/1358
Removed duplicate explanation of configuration properties in recipe. Checked all recipes for dupes. Validated change with local build.
[ ] Validate presentation with `bundle exec jekyll serve --livereload`
> remove dupe properties explanation

- assets/sass/_nav.scss
- For viewport width (992-1100 px), the navigation header was taking only 290px width. (Screenshot-1)
- But, we want it to take full space available for that viewport width range.
- This PR does that with a one-liner CSS change (Screenshot-2)
> Navigation UI bug fixed for specific viewport width range

- .semaphore/semaphore.yml
Looks like commit [613429f](https://github.com/confluentinc/kafka-tutorials/commit/613429fddbe6c144aec951200808aba722edbf49l) broke not deploying branches starting with `dependabot` - this PR is an attempt to fix this.
> MINOR: Fix for stopping dependabot PRs from deploying

- _layouts/recipe.html
- _layouts/tutorial.html
asana
https://app.asana.com/0/1109613500024910/1202815164044654
changing breadcrumbs on tutorials from back to recipes to back to tutorials
> Tutorial breadcrumb

- _data/harnesses/logistics/ksql-test.yml
- _data/harnesses/mainframe-offload/ksql-test.yml
- _data/harnesses/model-retraining/ksql-test.yml
- _data/harnesses/payment-status-check/ksql-test.yml
The handful of tests that query table output tend to be flaky due to the
async nature of ksqlDB. There's no guarantee that table result are
available after corresponding INSERTS. Other recipes that validate
via a stream query like "SELECT ... EMIT CHANGES LIMIT n;" aren't
susceptible to the same test flakiness since they will block on
n rows being emitted..
https://github.com/confluentinc/kafka-tutorials/issues/1328
N/A
N/A
> add a wait before validating ksqlDB recipe tests relying on table output

- _includes/tutorials/kafka-consumer-application/kafka/code/build.gradle
- _includes/tutorials/kafka-producer-application/kafka/code/build.gradle
The build script only contains a dependency for Kafka Streams.  The application works because KS pulls in the clients as a transitive dependency. Still, since the application does not use Kafka Streams, we should update the dependencies to pull in clients and remove the KS one explicitly.
Internal changes only to the `build.gradle` file no functional changes.
> BACKLOG: Cleaned up dependencies to include clients explicitly
